### ISSUE TITLE
[Intake] Create intake subsystem

### ISSUE THREAD

**Issue by brycecary** [cavineers/RobotCode2021#11]
* Create intake subsystem
* Must contain:
  * Conveyor belt
  * Intake wheels outside the bot

**Comment by Ryan4545** [comment]
Will both the conveyor and wheels be using the controller, or is it just the intake wheels and the conveyor belt is running constantly? We might need to talk to Intake to figure out their ideas.

**Comment by brycecary** [comment]
We'll probably find a time on Tuesday to talk through software with some of the subteams if they aren't busy.

This subsystem may also be split into 2; Intake; and Transport. Intake to handle the incoming balls, and Transport to handle the conveyor and hand-off to Shooter.

**Comment by brycecary** [comment]
Exclude the conveyor belt from this.
Should probably be a simple on/off for the intake bar, and a sensor to detect when it enters and gets passed to the transportation subsystem. The sensor may just be using power monitoring if it tends to happens to be the most reliable.

**Comment by brycecary** [comment]
1. You have two states defined: `m_currentMode` and `currentMotorState`. You also have an `enable` and `disable` methods plus a `setMotorState` method. The enable/disable don't do anything.
2. Switch all your class variables to the `m_` prefix.
3. Push state updates through Logger.
4. Add subsystem to `RobotContainer` like it is in `master`.
5. You can also remove the debug code in the `periodic` method.
6. Indentation on line 38.

A bunch of simple fixes; and make sure you use the `Organize Imports` command.
It may also help to merge master back into your branch so you resolve all those conflicts ahead of time.

**Comment by Ryan4545** [comment]
Updates pushed to Intake.
