### ISSUE TITLE
[Transportation] Create Transportation Subsystem

### ISSUE THREAD

**Issue by Ryan4545** [cavineers/RobotCode2021#14]
Create transportation subsystem that includes:

The conveyer belt motor (Intake) and the shooter feeder (Shooter).

**Comment by brycecary** [comment]
3/4" ball compression
~1 rotation:2 inches on belt

**Comment by Ryan4545** [comment]
Three (base, middle, top) optical sensors (infrared) to see when a ball enters the intake conveyer belt.

**Comment by Ryan4545** [comment]
Still need to code sensors and such...

But core of subsystem is ready for merge.
