### ISSUE TITLE
[Transportation] Code 3 Infrared Sensors to Detect PC in Conveyor Belt

### ISSUE THREAD

**Issue by Ryan4545** [cavineers/RobotCode2021#32]
Find and code the infrared sensors for the conveyor belt.

 Need to be able to find where the ball is located in the conveyor belt.

**Comment by Ryan4545** [comment]
Possible options listed below:

1. https://www.pololu.com/product/1134

**Comment by brycecary** [comment]
Actually ordered: https://www.pololu.com/product/1132

**Comment by Ryan4545** [comment]
Sensors have been added to the code in Transportation.java (the subsystem) but it still needs to be implemented across the conveyor system. Still need to use .get() on the sensors to change conveyor motor state.

Usage docs: https://docs.wpilib.org/en/stable/docs/software/sensors/digital-inputs-software.html
